### PR TITLE
Just adding a test

### PR DESCRIPTION
**Pull request by etwest**
Adding a test which verifies the parallelism is working correctly

### CODE REVIEW

**Comment by etwest** [comment]
Yeah something weird is going on here

**Comment by etwest** [comment]
So it seems that the number of graph workers you tell the circular queue about needs to match the actual number. Otherwise things go weird.

**Comment by Victor-C-Zhang** [comment]
> So it seems that the number of graph workers you tell the circular queue about needs to match the actual number. Otherwise things go weird.

Is this still the case now with the changes?

**Comment by etwest** [comment]
> > So it seems that the number of graph workers you tell the circular queue about needs to match the actual number. Otherwise things go weird.
> 
> Is this still the case now with the changes?

No

**Comment by Victor-C-Zhang** [comment]
> > > So it seems that the number of graph workers you tell the circular queue about needs to match the actual number. Otherwise things go weird.
> > 
> > 
> > Is this still the case now with the changes?
> 
> No

So this was just an artifact of buggy peek?

**Review by Victor-C-Zhang — APPROVED** [review]

**Comment by etwest** [comment]
> > > > So it seems that the number of graph workers you tell the circular queue about needs to match the actual number. Otherwise things go weird.
> > > 
> > > 
> > > Is this still the case now with the changes?
> > 
> > 
> > No
> 
> So this was just an artifact of buggy peek?

Seems like it

**Pull request merged**
